version: '3'

services:
  shoestore-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoestore
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - shoestore-postgres
      - redis
