server:
  port: 3000


#logging:
#  level:
#    root: ERROR
#  #    org.springframework.web: ERROR
#  #    com.auth0.example: TRACE


  error:
    whitelabel:
      enabled=false:
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: zR2dd6tWcYHzIGQYYvxRraVQep0ezqHg
            client-secret: e2wdSh-I_WcANzwfXviSRwwtAHWtXbIDPyip_t0rgvR64ZpN9pqPW9d75_1fTxNE
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-gzgdh7hw4udvv70u.us.auth0.com/
  flyway:
    enabled: true
  jooq:
    sql-dialect: Postgres
  datasource:
    ##This is for Docker
    url: jdbc:postgresql://shoestore-postgres:5432/shoestore?loggerLevel=OFF
    #url: jdbc:postgresql://localhost:5432/shoestore?loggerLevel=OFF

    username: postgres
    password: postgres
  data:
    redis:
      ##This is for Docker
      host: redis
      #host: localhost
      port: 6379
  mail:
    host: mail.privateemail.com
    port: 587
    username: hungllt@PreOrderPlatform.store
    password: Hung@160420
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


cloud:
    aws:
    region:
      main: us-east-2
    credentials:
      access-key: AKIA3XFLAEUIOGUTMHFX
      secret-key: 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
    end-point:
      uri: "http://www.foo.com"

